### ISSUE TITLE
Serial output corrupt within task

### ISSUE THREAD

**Issue by Steve-Squires** [discord-intech/FreeRTOS-Teensy4#2]
Hi Julian - tick rate now seems to be honoured - thanks.

New issue (was there before too): Serial output contains garbage or worse, crashes task. Steps to reproduce - modify blink_task.cpp example to output text during a task:

`
//------------------------------------------------------------------------------
/*
 * Thread 1, turn the LED off when signalled by thread 2.
 */
// Declare the thread function for thread 1.
static void Thread1(void* arg) {
  while (1) {

    // Wait for signal from thread 2.
    xSemaphoreTake(sem, portMAX_DELAY);

    Serial.println("T1");

    // Turn LED off.
    digitalWrite(LED_PIN, LOW);
  }
}
`

Bytes received:
`T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T1␀␀T`

Thanks,
Steve

**Comment by juliandesvignes** [comment]
Hi Steve,

I was confused at first because I have been using this port in a project with 3 UART lines and I never had any problem (albeit on 1kHz tickrate). But I could definitely reproduce the error you demonstrated. And after a bit of analysis I realized that the problem comes from calling `usb_serial_write(void*, uint32)` twice in a row in a task.

Basically, calling `Serial.println(s)` is doing `Serial.print(s)` and `Serial.println()`, the latter printing the return carriage and new line chars. This is hence calling the underlying weak reference `write(buf, size)` twice in a row, which (in the case of the Serial symbol on Teensy4) is calling `usb_serial_write(buf, size)`. This last function is quite complex because it involves quite a bit of USB timing that uses Teensyduino's systicking, and I need to properly fix the latter which could take me some time.

In the meanwhile, if you require to use the USB Serial in your task, you can append the `\r\n` to your buffer (so "T1\r\n" instead of "T1") and call `Serial.print` to have the same effect as `Serial.println` while doing only one call to `usb_serial_write`. If you need to do multiple writes, please temporarily use a `vTaskDelay` of a couple ticks between calls to allow the systick to properly set itself.

I will keep this issue updated.

Best of luck,
Julian

**Comment by juliandesvignes** [comment]
You can also flush with `Serial.flush()` after a print, it's more efficient than waiting a few ticks.

**Comment by Steve-Squires** [comment]
Hello Julian,

I can confirm that `Serial.flush()` appears to work.

The modified example is:
`static void Thread1(void* arg) {
  while (1) {

    // Wait for signal from thread 2.
    xSemaphoreTake(sem, portMAX_DELAY);

    Serial.print("T1234567890");
    Serial.flush();
    Serial.println();
    Serial.flush();

    // Turn LED off.
    digitalWrite(LED_PIN, LOW);
  }
}`

Many thanks,
Steve

**Comment by juliandesvignes** [comment]
Thanks for the confirmation, but this is definitely not a good fix.

After a lot of debugging, I have found out that the problem is due to unaligned memory access, the compiler on`-O1` optimization level seems to setup the `usb_serial_write` function so that it causes unaligned memory access on the `memcpy` from the given buffer to the USB TX buffer. Flushing the buffer (by either asking for it or waiting for the usb_timer to reach 0) empties the USB TX buffer, making the next `memcpy` to be aligned.

Technically the CM7 is capable of unaligned memory accesses, but using the memory map associated with FreeRTOS (stack is not in DTCM) seems to cause this MemFault. I tried to setup the VFP properly as per the ARM CM7 documentation, but to no avail.

Compiling in `-O0` seems to do the trick (`-DTEENSY_OPT_DEBUG`), so I'll temporarily add a pre-processor check to force the user to compile with this option.
If you are using Arduino IDE, simply select `Debug` in `Tools -> Optimize`.
If you are using PlatformIO , add `build_flags = -DTEENSY_OPT_DEBUG` under `[env]` in your `platformio.ini`.

If you do that, you can use the Arduino library as usual, no need to flush anymore.

**Comment by Steve-Squires** [comment]
Hi Julian,

Ah - you edited the post - the first email I received had the suggestion to use `-DTEENSY_OPT_SMALLEST_CODE `. This did not work. I am using `-DTEENSY_OPT_DEBUG` and the sample works.

Thanks,
Steve

**Comment by juliandesvignes** [comment]
Yes, sorry, I made a mistake.

**Comment by Steve-Squires** [comment]
Hi Julian, I see that Teensyduino 1.49 has just been released and one of the fixes relates to moving USB serial buffers from ITCM to OCRAM on Teensy 4.0.
I will investigate...
Steve

**Comment by juliandesvignes** [comment]
Hi Steve, thanks for the update. I checked and ran my tests, but sadly the same problem is still present. It's even worse now, since a misaligned call on AXI memory now triggers a MemFault. The problem is linked closely to the memcpy implementation integrated in Teensyduino, as it does not seems to like being ran on the PSP stack instead of the MSP stack. Or I might be wrong, still investigating on this.

By the way, the latest commit fixes the crash when using `-DTEENSY_OPT_SMALLEST_CODE`, this has `-O2` optimizations.

**Comment by juliandesvignes** [comment]
I can confirm this is linked to `memcpy-armv7m.S` in teensyduino, using the built-in memcpy of gcc-arm-none-eabi works flawlessly even in `-O3`.

**Comment by juliandesvignes** [comment]
I think this is linked to the fact that if `__OPTIMIZE_SIZE__` isn't declared (this is declared in `-Os`), the linker uses the built-in `memset` instead of the one included in teensyduino., creating a huge gap between the two symbols. The `memset.S` in teensyduino is guarded by  `#if defined (__OPTIMIZE_SIZE__)`. Defining it at compile time using `-D__OPTIMIZE_SIZE__` fixes the issue in every optimization mode, even `TEENSY_OPT_FASTEST`.

I still do not like to force users to add a compile-time define in their projects, I'll try to find a way around this.

**Comment by juliandesvignes** [comment]
This offset between `memcpy` and `memset` seems to have been the problem. Adding them in the library forces the compiler to put them next to each other in the ITCM. That seems to fix the issue on both teensyduino 1.48 and 1.49, no specific define needed. I committed the fix just now, please test it and close the issue if it works for you.

**Comment by Steve-Squires** [comment]
Great work Julian. I'm waiting for the fix to propagate through to platformio (still on 10.0.3 and I don't want to copy manually). I'll let you know as soon I have it but your commentary makes sense.
Thanks,
Steve
p.s. did you get my external email?

**Comment by Steve-Squires** [comment]
I just manually downloaded and re-built with 10.0.4. All seems to work - thank you!

FYI, my simple test code is:
`/*
 * Example to demonstrate thread definition, semaphores, and thread sleep.
 */
#include <FreeRTOS_TEENSY4.h>

// The LED is attached to pin 13 on the Teensy 4.0
const uint8_t LED_PIN = 13;

// Declare a semaphore handle.
SemaphoreHandle_t sem;

// Include queue support
#include <queue.h>

// Define a struct
struct pinRead
{
  int pin;
  int value;
};

/* 
 * Declaring a global variable of type QueueHandle_t 
 * 
 */
QueueHandle_t structQueue;

/**
 * Analog read task for Pin A0
 * Reads an analog input on pin 0 and send the readed value through the queue.
 * See Blink_AnalogRead example.
 */
void TaskAnalogReadPin0(void *pvParameters)
{
  (void)pvParameters;

  Serial.println("Started TaskAnalogReadPin0");

  for (;;)
  {
    // Read the input on analog pin 0:
    struct pinRead currentPinRead;
    currentPinRead.pin = 0;
    currentPinRead.value = analogRead(A0);

    /**
     * Post an item on a queue.
     * https://www.freertos.org/a00117.html
     */
    xQueueSend(structQueue, &currentPinRead, portMAX_DELAY);

    // One tick delay (15ms) in between reads for stability
    vTaskDelay(pdMS_TO_TICKS(1000));
  }
}

/**
 * Analog read task for Pin A1
 * Reads an analog input on pin 1 and send the readed value through the queue.
 * See Blink_AnalogRead example.
 */
void TaskAnalogReadPin1(void *pvParameters)
{
  (void)pvParameters;

  Serial.println("Started TaskAnalogReadPin1");

  for (;;)
  {
    // Read the input on analog pin 1:
    struct pinRead currentPinRead;
    currentPinRead.pin = 1;
    currentPinRead.value = analogRead(A1);

    /**
     * Post an item on a queue.
     * https://www.freertos.org/a00117.html
     */
    xQueueSend(structQueue, &currentPinRead, portMAX_DELAY);

    // One tick delay (15ms) in between reads for stability
    vTaskDelay(pdMS_TO_TICKS(1000));
  }
}

/**
 * Serial task.
 * Prints the received items from the queue to the serial monitor.
 */
void TaskSerial(void *pvParameters)
{
  (void)pvParameters;

  Serial.println("Started TaskSerial");

  for (;;)
  {

    struct pinRead currentPinRead;

    /**
     * Read an item from a queue.
     * https://www.freertos.org/a00118.html
     */
    if (xQueueReceive(structQueue, &currentPinRead, portMAX_DELAY) == pdPASS)
    {

      Serial.print("Pin ");
      Serial.print(currentPinRead.pin);
      Serial.print(" Value: ");
      Serial.print(currentPinRead.value);
      Serial.println();
    }

    vTaskDelay(pdMS_TO_TICKS(1));
  }
}

/* 
 * Blink task. 
 * See Blink_AnalogRead example. 
 */
void TaskBlink(void *pvParameters)
{
  (void)pvParameters;

  Serial.println("Started TaskBlink");

  pinMode(LED_BUILTIN, OUTPUT);

  for (;;)
  {
    digitalWrite(LED_BUILTIN, HIGH);
    vTaskDelay(pdMS_TO_TICKS(400));
    digitalWrite(LED_BUILTIN, LOW);
    vTaskDelay(pdMS_TO_TICKS(100));
  }
}

//------------------------------------------------------------------------------
void setup()
{

  /**
   * Create a queue.
   * https://www.freertos.org/a00116.html
   */
  structQueue = xQueueCreate(100,                   // Queue length
                             sizeof(struct pinRead) // Queue item size
  );

  if (structQueue != NULL)
  {

    // Create task that consumes the queue if it was created.
    xTaskCreate(TaskSerial, // Task function
                "Serial",   // A name just for humans
                128,        // This stack size can be checked & adjusted by reading the Stack Highwater
                NULL,
                1, // Priority, with 3 (configMAX_PRIORITIES - 1) being the highest, and 0 being the lowest.
                NULL);

    // Create task that publish data in the queue if it was created.
    xTaskCreate(TaskAnalogReadPin0, // Task function
                "AnalogReadPin0",   // Task name
                128,                // Stack size
                NULL,
                2, // Priority
                NULL);

    // Create other task that publish data in the queue if it was created.
    xTaskCreate(TaskAnalogReadPin1, // Task function
                "AnalogReadPin1",   // Task name
                128,                // Stack size
                NULL,
                2, // Priority
                NULL);
  }

  xTaskCreate(TaskBlink, // Task function
              "Blink",   // Task name
              128,       // Stack size
              NULL,
              0, // Priority
              NULL);

  pinMode(LED_BUILTIN, OUTPUT);
  for (size_t i = 0; i < 10; i++)
  {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(50);
    digitalWrite(LED_BUILTIN, LOW);
    delay(50);
  }

  // Init Arduino serial
  Serial.begin(9600);

  while (!Serial)
  {
    delay(1);
  }
  

  // debug by LED
  pinMode(LED_BUILTIN, OUTPUT);
  for (size_t i = 0; i < 10; i++)
  {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(100);
    digitalWrite(LED_BUILTIN, LOW);
    delay(100);
  }

  Serial.println("Starting scheduler");
  Serial.flush();

  // start scheduler
  vTaskStartScheduler();

  Serial.println("Insufficient RAM");

  while (1)
    ;
}
//------------------------------------------------------------------------------
// WARNING idle loop has a very small stack (configMINIMAL_STACK_SIZE)
// loop must never block
void loop()
{
  // Not used.
}`
